### ISSUE TITLE
Update to Lancer module 2.x?

### ISSUE THREAD

**Issue by JovianSunrise** [BadIdeasBureau/lancer-alt-structure#6]
I'm getting a javascript error from this module after updating to v2.1.7 of the Lancer module.
It looks like the Structure/Stress function has changed?

Any chance we'll get a new version for 2.x?

**Comment by BadIdeasBureau** [comment]
Working on this now - the latest commit on the repo is a "probably working" version, which I'm hoping to get some time to test later today and once I've done that I'll push a release out (today is my day of "get my home game up to v11 / Lancer 2.0", and this is part of that)

**Comment by BadIdeasBureau** [comment]
New release should work on lancer v2

**Comment by JovianSunrise** [comment]
Thanks for the quick turn around!  This is so nice to have.
