### ISSUE TITLE
Module doesn't match current version of Maria's Alternative Ruleset

### ISSUE THREAD

**Issue by letheka** [BadIdeasBureau/lancer-alt-structure#7]
Hi, thanks for making this module and updating it to work with Lancer v2 for Foundry. 

However, the tables in the module don't seem to match the current version of Maria's Alternative Ruleset as written in the google doc linked in the README.md, and also in the PDF available on itch.io (at https://esbionarshadow.itch.io/gms-crisis-catalogue).

For example, a direct hit with 3+ structure remaining should according to Maria's current rules result in _"Your mech is IMPAIRED and SLOWED until the end of your next turn"_, but in this module, it has the effect _"Your mech is STUNNED until the end of your next turn"_ (like the structure table in the core Lancer rulebook.)

Are there multiple versions of Maria's rules out there, and this module is based on a different one? Or is this an oversight?

Thanks.

**Comment by BadIdeasBureau** [comment]
Fixed in latest release (thanks to @Z3nner 's PR)
